#!/bin/bash

OKBLUE='\033[94m'
OKRED='\033[91m'
OKGREEN='\033[92m'
OKORANGE='\033[93m'
RESET='\e[0m'

cat << "EOF"
                                     )
                            )      ((     (
                           (        ))     )
                    )       )      //     (
               _   (        __    (     ~->>
        ,-----' |__,_~~___<'__`)-~__--__-~->> <
        | //  : | -__   ~__ o)____)),__ - '> >-  >
        | //  : |- \_ \ -\_\ -\ \ \ ~\_  \ ->> - ,  >>
        | //  : |_~_\ -\__\ \~'\ \ \, \__ . -<-  >>
        `-----._| `  -__`-- - ~~ -- ` --~> >
         _/___\_    //)_`//  | ||]
   _____[_______]_[~~-_ (.L_/  ||
  [____________________]' `\_,/'/
    ||| /          |||  ,___,'./
    ||| \          |||,'______|
    ||| /          /|| I==||
    ||| \       __/_||  __||__
-----||-/------`-._/||-o--o---o---
> \ /           Flameapk :  Artifical Intelligence Suite for Android Application Security
(_,-'`> .'      Authors  :  1N3 - Haroon Awan 
(_,'            Usage    :  flameapk android_file_here

EOF


echo -e "$RESET"

echo -e "$OKRED [+] Unpacking In Progress"
echo -e "$OKRED $RESET"
unzip $PWD/$1 -d $PWD/$1-unzipped/ 
baksmali d $PWD/$1-unzipped/classes.dex -o $PWD/$1-unzipped/classes.dex.out/ 2> /dev/null
echo ""
echo -e "$OKORANGE [>] Conversation In Progress"
echo -e ""
d2j-dex2jar $PWD/$1 -o $PWD/$1.jar --force 
echo ""
echo -e "$OKORANGE [>] Decompiling In Progress"
echo -e ""
jadx $PWD/$1 -j $(grep -c ^processor /proc/cpuinfo) -d $PWD/$1-jadx/ > /dev/null
echo ""
echo -e "$OKORANGE [>] Unpacking In Progress"
echo -e ""
apktool d $PWD/$1 -o $PWD/$1-unpacked/ -f 
echo ""
echo -e "$OKGREEN [>] Displaying Data "
echo -e ""
find $PWD/$1 | egrep 'apk|class' --color=auto 2>/dev/null
echo ""
echo -e "$OKRED [>] Displaying AndroidManifest.xml"
echo -e ""
cat $PWD/$1-unpacked/AndroidManifest.xml
echo ""
echo -e "$OKRED [>] Displaying Package Info in AndroidManifest.xml"
echo -e ""
egrep -i 'package=' $PWD/$1-unpacked/AndroidManifest.xml --color=auto 2>/dev/null
echo ""
echo -e "$OKRED [>] Displaying Activities in AndroidManifest.xml"
echo -e ""
egrep -i 'activity ' $PWD/$1-unpacked/AndroidManifest.xml --color=auto 2>/dev/null
echo ""
echo -e "$OKRED [>] Displaying Services in AndroidManifest.xml"
echo -e ""
egrep -i 'service ' $PWD/$1-unpacked/AndroidManifest.xml --color=auto 2>/dev/null
echo ""
echo -e "$OKRED [>] Displaying Content Providers in AndroidManifest.xml"
echo -e ""
egrep -i 'provider' $PWD/$1-unpacked/AndroidManifest.xml --color=auto 2>/dev/null
echo ""
echo -e "$OKRED [>] Displaying Broadcast Receivers in AndroidManifest.xml"
echo -e ""
egrep -i 'receiver' $PWD/$1-unpacked/AndroidManifest.xml --color=auto 2>/dev/null
echo ""
echo -e "$OKRED [>] Displaying Intent Filter Actions in AndroidManifest.xml"
echo -e ""
egrep -i 'action|category' $PWD/$1-unpacked/AndroidManifest.xml --color=auto 2>/dev/null
echo ""
echo -e "$OKRED [>] Displaying Permissions in AndroidManifest.xml"
echo -e ""
egrep -i 'android.permission' $PWD/$1-unpacked/AndroidManifest.xml --color=auto 2>/dev/null
echo ""
echo -e "$OKRED [>] Displaying Exports in AndroidManifest.xml"
echo -e ""
egrep -i 'exported="true"' $PWD/$1-unpacked/AndroidManifest.xml --color=auto 2>/dev/null
echo ""
echo -e "$OKRED [>] Displaying Backups in AndroidManifest.xml"
echo -e ""
egrep -i 'backup' $PWD/$1-unpacked/AndroidManifest.xml --color=auto 2>/dev/null
echo ""
#echo -e "$OKRED [>] Displaying all classes and methods"
#echo -e ""
#dexdump -f $PWD/$1-unzipped/classes.dex -l xml | egrep 'class name' --color=auto 2>/dev/null
#dexdump -f $PWD/$1-unzipped/classes.dex -l xml | egrep 'method name' --color=auto 2>/dev/null

################## DEVICE INFO
echo ""
echo -e "$OKRED [>] Searching for DeviceId references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH 'getDeviceId' $a --color=auto 2>/dev/null; done;
echo ""
################## INTENT REFERENCES

echo -e "$OKRED [>] Searching for android.intent references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH 'android\.intent' $a --color=auto 2>/dev/null; done;
echo ""
################# COMMAND EXECUTION REFERENCES

echo -e "$OKRED [>] Searching for command execution references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH 'Runtime.getRuntime\(\).exec' $a --color=auto 2>/dev/null; done;
echo ""
################# SQLITE REFERENCES

echo -e "$OKRED [>] Searching for SQLiteDatabase references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH 'SQLiteDatabase' $a --color=auto 2>/dev/null; done;
echo ""
################# LOGGING REFERENCES

echo -e "$OKRED [>] Searching for Log.d references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH 'log\.d|Log\.' $a --color=auto 2>/dev/null; done;
echo ""
################# CONTENT PROVIDERS

echo -e "$OKRED [>] Displaying content providers"
echo -e ""
egrep -nH 'content://' -R $PWD/$1* --color=auto 2>/dev/null
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH '://' $a --color=auto 2>/dev/null; done;
echo ""
################# BROADCAST RECEIVERS

echo -e "$OKRED [>] Searching for sendBroadcast references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH 'sendBroadcast' $a --color=auto 2>/dev/null; done;
echo ""
################# SERVICE REFERENCES

echo -e "$OKRED [>] Searching for Service references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH 'stopService|startService' $a --color=auto 2>/dev/null; done;
echo ""
################# FILE REFERENCES

echo -e "$OKRED [>] Searching for file:// references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH 'file://' $a --color=auto 2>/dev/null; done;
echo ""
echo -e "$OKRED [>] Searching for getSharedPreferences references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH getSharedPreferences $a --color=auto 2>/dev/null; done;
echo ""
echo -e "$OKRED [>] Searching for getExternal references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -iH getExternal $a --color=auto 2>/dev/null; done;
echo ""
################# CRYPTO REFERENCES

echo -e "$OKRED [>] Searching for Crpto references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH 'crypto\.' $a --color=auto 2>/dev/null; done;
echo ""
echo -e "$OKRED [>] Searching for MessageDigest references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH 'MessageDigest' $a --color=auto 2>/dev/null; done;
echo ""
echo -e "$OKRED [>] Searching for java.util.Random references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH 'java\.util\.Random' $a --color=auto 2>/dev/null; done;
echo ""
echo -e "$OKRED [>] Searching for Base64 references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH 'Base64' $a --color=auto 2>/dev/null; done;
echo ""
echo -e "$OKRED [>] Searching for Hex references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH 'Hex|hex\.' $a --color=auto 2>/dev/null; done;
echo ""
################# HARDCODED SECRETS

echo -e "$OKRED [>] Searching for hardcoded secrets"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -inH 'secret|password|username' $a --color=auto 2>/dev/null; done;
echo ""
echo -e "$OKRED [>] Searching for sensitive information"
echo -e ""
#strings $PWD/$1 | egrep -i 'user|pass|key|login|pwd|log' --color=auto  2>/dev/null
strings $PWD/$1 > $PWD/$1-strings.txt
echo ""
################# URL VULNERABILITIES

echo -e "$OKRED [>] Searching for URL's"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH 'http:|https:' $a --color=auto 2>/dev/null; done;
echo ""
echo -e "$OKRED [>] Searching for HTTP headers"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH 'addHeader' $a --color=auto 2>/dev/null; done;
echo ""
echo -e "$OKRED [>] Searching for UDP and TCP Sockets"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH '\.connect\(|\.disconnect|serverSocket|DatagramSocket' $a --color=auto 2>/dev/null; done;
echo ""
################# SSL REFERENCES

echo -e "$OKRED  [>] Searching for client certificates"
echo -e ""
find $PWD/$1-unzipped/ | egrep '\.pkcs|\.p12|\.cer|\.der' --color=auto 2>/dev/null
echo ""
echo -e "$OKRED  [>] Searching for SSL certificate pinning"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH getCertificatePinningSSL $a --color=auto 2>/dev/null; done;
echo ""
echo -e "$OKRED [>]  Searching for SSL connections"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH 'ssl\.SSL' $a --color=auto 2>/dev/null; done;

################# WEBVIEW REFERENCES

echo -e "$OKRED [>] Searching for WebView activity"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH WebView $a --color=auto 2>/dev/null; done;
echo ""
echo -e "$OKRED [>] Searching for addJavascriptInterface references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH addJavascriptInterface $a --color=auto 2>/dev/null; done;
echo ""
echo -e "$OKRED [>] Searching for setJavaScriptEnabled references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH setJavaScriptEnabled $a --color=auto 2>/dev/null; done;
echo ""
################# MISCELLANEOUS REFERENCES

echo -e "$OKRED [>] Searching for Domain references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH domain $a --color=auto 2>/dev/null; done;
echo ""
echo -e "$OKRED [>] Searching for Bucket references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH buckets $a --color=auto 2>/dev/null; done;
echo ""
echo -e "$OKRED [>] Searching for Storage references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH storage $a --color=auto 2>/dev/null; done;
echo ""
echo -e "$OKRED [>] Searching for Api references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH api $a --color=auto 2>/dev/null; done;
echo ""
echo -e "$OKRED [>] Searching for Spi references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH spi $a --color=auto 2>/dev/null; done;
echo ""
echo -e "$OKRED [>] Searching for FTP references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH ftp $a --color=auto 2>/dev/null; done;
echo ""
echo -e "$OKRED [>] Searching for Endpoint references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH endpoint $a --color=auto 2>/dev/null; done;
echo ""
echo -e "$OKRED [>] Searching for Endpoint references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH Endpoint $a --color=auto 2>/dev/null; done;
echo ""
echo -e "$OKRED [>] Searching for Endpoint references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH EndPoint $a --color=auto 2>/dev/null; done;
echo ""
echo -e "$OKRED [>] Searching for Gopher references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH gopher $a --color=auto 2>/dev/null; done;
echo ""
echo -e "$OKRED [>] Searching for HTTPS references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH https $a --color=auto 2>/dev/null; done;
echo ""
echo -e "$OKRED [>] Searching for HTTPS references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH http $a --color=auto 2>/dev/null; done;
echo ""
echo -e "$OKRED [>] Searching for SQL Database references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH database $a --color=auto 2>/dev/null; done;
echo ""
echo -e "$OKRED [>] Searching for Subdomain references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH subdomain $a --color=auto 2>/dev/null; done;
echo ""
echo -e "$OKRED [>] Searching for EMAIL references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -E -o "\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b" $a --color=auto 2>/dev/null; done;
echo ""
echo -e "$OKRED [>] Searching for Google references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH google $a --color=auto 2>/dev/null; done;
echo ""
echo -e "$OKRED [>] Searching for Facebook references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH facebook $a --color=auto 2>/dev/null; done;
echo ""
echo -e "$OKRED [>] Searching for Ali BaBa references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH alibaba $a --color=auto 2>/dev/null; done;
echo ""
echo -e "$OKRED [>] Searching for SSH references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH ssh $a --color=auto 2>/dev/null; done;
echo ""
echo -e "$OKRED [>] Searching for Dump references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH dump $a --color=auto 2>/dev/null; done;
echo ""
echo -e "$OKRED [>] Searching for DB references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH db $a --color=auto 2>/dev/null; done;
echo ""
echo -e "$OKRED [>] Searching for HTTP Put references"
echo -e ""
for a in `find $PWD/$1-jadx | egrep -i .java`; do egrep -nH put $a --color=auto 2>/dev/null; done;
echo ""
echo -e "$OKRED DONE!"
echo -e ""
